name: MorphPlugin
version: 1.0.3
main: de.vmoon.morphplugin.MorphPlugin
api-version: '1.20'
authors: [VoidableMoon884]
description: A Morph Plugin by VoidableMoon884
website: https://morph.vmoon.de/
commands:
  morph: